[general]
import = [
    # "~/.config/alacritty/monokai-pro.toml",
    # "~/.config/alacritty/monokai-charcoal.toml",
    # "~/.config/alacritty/rose-pine.toml",
    "~/.config/alacritty/rose-pine-moon.toml",
    # "~/.config/alacritty/nord.toml",
    # "~/.config/alacritty/gruvbox.toml",
]

[font]
size = 10

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/bash"

[window.dimensions]
columns = 80
lines = 24

[env]
TERM = "xterm-256color"

[terminal]
